[package]
name = "vxdiff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "*"
crossterm = "*"
rand = "*"
string-interner = "*"
tui = "*"
unicode-segmentation = "*"
unicode-width = "*"
float-ord = "*"
