[package]
name = "vxdiff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "*"
clap = {version = "*", features = ['derive']}
console = "*"
crossterm = "*"
float-ord = "*"
memchr = "*"
rand = "*"
regex = "*"
string-interner = "*"
tui = "*"
unicode-segmentation = "*"
unicode-width = "*"
